#define MAINPREFIX DA
#define PREFIX DAC
#define ADDON PREFIX##_##COMPONENT

#include "\DA\DAC\core\script_version.hpp"

#define VERSION     MAJOR.MINOR
#define VERSION_STR MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_ARR MAJOR,MINOR,PATCHLVL,BUILD

#define REQUIRED_VERSION 2.14

#ifndef COMPONENT_BEAUTIFIED
    #define COMPONENT_BEAUTIFIED COMPONENT
#endif