#define MAINPREFIX DA
#define PREFIX DAC

#include "\x\cba\addons\main\script_macros_common.hpp"
#include "\DA\DAC\Common\script_version.hpp"

#define VERSION_ARR MAJOR,MINOR,PATCHLVL,BUILD

#define REQUIRED_VERSION 2.14

#ifndef COMPONENT_BEAUTIFIED
    #define COMPONENT_BEAUTIFIED COMPONENT
#endif

#define COMPONENT_NAME PREFIX - COMPONENT_BEAUTIFIED
#define QCOMPONENT_NAME QUOTE(COMPONENT_NAME)

#ifdef SUBCOMPONENT
    #ifndef SUBCOMPONENT_BEAUTIFIED
        #define SUBCOMPONENT_BEAUTIFIED SUBCOMPONENT
    #endif
    #define SUBCOMPONENT_NAME COMPONENT_NAME (SUBCOMPONENT_BEAUTIFIED)
    #define QSUBCOMPONENT_NAME QUOTE(SUBCOMPONENT_NAME)
#endif

#define GFUNC(FNCNAME) TRIPLES(PREFIX,fnc,FNCNAME)